const allCharacters = [
  {
    char: "Q",
    type: "letter",
    error: 255,
    active: true,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "7",
    type: "number",
    error: 255,
    active: true,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "Z",
    type: "letter",
    error: 255,
    active: true,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "G",
    type: "letter",
    error: 255,
    active: true,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "0",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "9",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "8",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "O",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "1",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "J",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "P",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "W",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: ".",
    type: "symbol",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "L",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "R",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "A",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "M",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "6",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "B",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "/",
    type: "symbol",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "X",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "D",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "=",
    type: "symbol",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "Y",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "C",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "K",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "N",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "2",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "3",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "?",
    type: "symbol",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "F",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "U",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "4",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "5",
    type: "number",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "V",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "H",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "S",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "I",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "T",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
  {
    char: "E",
    type: "letter",
    error: 255,
    active: false,
    avgResponseTime: 0,
    mistakes: 0,
    attempts: 0,
  },
];
